version: 4.3.0.{build}
image: Visual Studio 2019 preview
clone_folder: c:\projects\nlog
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  assembly_version: '4.0.0.0'
  file_version: '{version}'
  package_version: '4.3.0'
  informational_version: '4.3.0'
  version: '4.3.0'
skip_tags: true
build_script:	
  - ps: msbuild /t:restore,build /p:Configuration=Release /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /maxcpucount /v:m
test_script:
  - nuget.exe install OpenCover -ExcludeVersion
  - OpenCover\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"\"c:\projects\nlog\NLog.Windows.Forms.Tests\bin\Release\net452\NLog.Windows.Forms.Tests.dll\" -appveyor -noshadow"  -returntargetcode -filter:"+[NLog.Windows.Forms]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"
 
artifacts:
  - path: '**\NLog.*.nupkg'
  - path: '**\NLog.*.snupkg'

deploy:
- provider: NuGet
  api_key:
    secure: N/3SLEg4r4QlbIVrI6epIHgv2KfwkwkrIUeLRyqS8D3AkC29Ql86NMkHxWOfcmUM
  on:
    branch: master
